const API='/api/accounts';
const T2C={'أمريكي':'USD','هونغ كونغ':'HKD','ياباني':'JPY','سوداني':null};
const ER={USD:1,HKD:0.128,JPY:0.0067,SAR:0.27,AED:0.27,EUR:1.08,EGP:0.021,GBP:1.27,TRY:0.03,CAD:0.74,AUD:0.66};
const CS={USD:'$',HKD:'HK$',JPY:'¥',SAR:'﷼',AED:'د.إ',EUR:'€',EGP:'ج.م',GBP:'£',TRY:'₺',CAD:'C$',AUD:'A$'};
const CN={USD:'دولار أمريكي',HKD:'دولار هونغ كونغ',JPY:'ين ياباني',SAR:'ريال سعودي',AED:'درهم إماراتي',EUR:'يورو',EGP:'جنيه مصري',GBP:'جنيه إسترليني',TRY:'ليرة تركية',CAD:'دولار كندي',AUD:'دولار أسترالي'};
const AC=['سوداني','أمريكي','هونغ كونغ','ياباني'];
let accounts=[],editIndex=-1,syncTimer=null,idb=null;
let advancedFilter={active:false,priceFrom:null,priceTo:null,dateFrom:null,dateTo:null};
const DBN='AmjadDB',ST='backup';
function openIDB(){return new Promise((r,j)=>{const q=indexedDB.open(DBN,1);q.onerror=()=>j(q.error);q.onsuccess=()=>{idb=q.result;r(idb)};q.onupgradeneeded=e=>{if(!e.target.result.objectStoreNames.contains(ST))e.target.result.createObjectStore(ST)}})}
function idbSave(d){return new Promise((r,j)=>{if(!idb)return r();const t=idb.transaction(ST,'readwrite');t.objectStore(ST).put(d,'data');t.oncomplete=()=>r();t.onerror=()=>j(t.error)})}
function idbLoad(){return new Promise((r,j)=>{if(!idb)return r(null);const t=idb.transaction(ST,'readonly');const q=t.objectStore(ST).get('data');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
function setSS(s){const e=document.getElementById('ss');if(!e)return;if(s==='online'){e.className='ss online';e.textContent='✅ متزامن'}else if(s==='offline'){e.className='ss offline';e.textContent='⚠️ غير متصل'}else{e.className='ss syncing';e.textContent='⏳ جاري'}}
async function saveData(){localStorage.setItem('amjad_final',JSON.stringify(accounts));try{await idbSave(accounts)}catch(e){}}
function showToast(m,t2){t2=t2||'success';const e=document.getElementById('tst');if(!e)return;e.textContent=m;e.className='ts '+t2;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3500)}
function switchTab(n,b){document.querySelectorAll('.tc').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tbb').forEach(x=>x.classList.remove('active'));const tab=document.getElementById('tab-'+n);if(tab)tab.classList.add('active');if(b)b.classList.add('active')}
function filterByType(t2){const ft=document.getElementById('ft');if(ft)ft.value=t2;renderAccounts()}
function updateFF(){const t2=document.getElementById('ti').value;const c=T2C[t2];const pg=document.getElementById('pg');const p=document.getElementById('pi');if(!pg||!p)return;if(c===null){pg.classList.add('hn');p.value=''}else{pg.classList.remove('hn')}updateCurrencyDisplay()}
function updateCurrencyDisplay(){const t2=document.getElementById('ti').value;const c=T2C[t2];const ci=document.getElementById('ci');if(!ci)return;if(c===null){ci.innerHTML='<option value="FREE">Free</option>';ci.disabled=true;return}ci.disabled=false;let opts='';const allCur=['USD','HKD','JPY','SAR','AED','EUR','EGP','GBP','TRY','CAD','AUD'];allCur.forEach(cur=>{opts+='<option value="'+cur+'"'+(cur===c?' selected':'')+'>'+CS[cur]+' '+CN[cur]+'</option>'});ci.innerHTML=opts}
function toggleTheme(){document.body.classList.toggle('light-mode');const l=document.body.classList.contains('light-mode');const tb=document.getElementById('tb');if(tb)tb.textContent=l?'☀️':'🌙';localStorage.setItem('amjad_theme',l?'light':'dark')}
if(localStorage.getItem('amjad_theme')==='light'){document.body.classList.add('light-mode');const tb=document.getElementById('tb');if(tb)tb.textContent='☀️'}
function extractEmail(tx){const m=tx.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/);return m?m[0]:null}
function extractPrice(tx,e){const c=tx.replace(e,' ');const m=c.match(/(\d+(?:[.,]\d+)?)/g);if(!m)return null;for(let x of m){const n=parseFloat(x.replace(',','.'));if(!isNaN(n)&&n>=0&&n<10000000)return n}return null}
function extractType(tx){const x=tx.toLowerCase();if(x.includes('سوداني')||x.includes('sudan')||x.includes('sd'))return 'سوداني';if(x.includes('هونغ')||x.includes('هونج')||x.includes('hong')||x.includes('hk'))return 'هونغ كونغ';if(x.includes('ياباني')||x.includes('japan')||x.includes('jp'))return 'ياباني';if(x.includes('أمريكي')||x.includes('امريكي')||x.includes('usa')||x.includes('us'))return 'أمريكي';return null}
function extractCurrency(tx){const x=tx.toLowerCase();if(x.includes('ريال')||x.includes('sar')||x.includes('﷼'))return 'SAR';if(x.includes('درهم')||x.includes('aed')||x.includes('د.إ'))return 'AED';if(x.includes('يورو')||x.includes('eur')||x.includes('€'))return 'EUR';if(x.includes('جنيه مصري')||x.includes('egp')||x.includes('ج.م'))return 'EGP';if(x.includes('إسترليني')||x.includes('gbp')||x.includes('£'))return 'GBP';if(x.includes('تركي')||x.includes('try')||x.includes('₺'))return 'TRY';if(x.includes('كندي')||x.includes('cad'))return 'CAD';if(x.includes('أسترالي')||x.includes('aud'))return 'AUD';return null}
function getUSD(a){if(!a.currency||a.currency==='FREE')return 0;return parseFloat(a.price||0)*(ER[a.currency]||1)}
function esc(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function isValidEmail(e){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)}
function formatDate(d){if(!d)return '';const dt=new Date(d);return dt.toLocaleDateString('ar-EG',{year:'numeric',month:'2-digit',day:'2-digit'})}
function getFiltered(){const s=document.getElementById('si')?.value.toLowerCase()||'';const f=document.getElementById('ft')?.value||'all';return accounts.filter(a=>{const mS=a.email.toLowerCase().includes(s);const mT=f==='all'||a.type===f;let mAF=true;if(advancedFilter.active){const usd=getUSD(a);if(advancedFilter.priceFrom!==null&&usd<advancedFilter.priceFrom)mAF=false;if(advancedFilter.priceTo!==null&&usd>advancedFilter.priceTo)mAF=false;if(advancedFilter.dateFrom&&a.created_at&&new Date(a.created_at)<new Date(advancedFilter.dateFrom))mAF=false;if(advancedFilter.dateTo&&a.created_at&&new Date(a.created_at)>new Date(advancedFilter.dateTo+'T23:59:59'))mAF=false}return mS&&mT&&mAF})}
function renderAccounts(){const filtered=getFiltered();renderCards(filtered);renderTable(filtered);renderCharts();updateStats();const fc=document.getElementById('fc');if(fc)fc.textContent=filtered.length+'/'+accounts.length;if(typeof updatePointsDisplay==='function')setTimeout(updatePointsDisplay,200)}
function renderCards(f){const c=document.getElementById('cc');if(!c)return;if(f.length===0){c.innerHTML='<div class="es"><span class="ic">📭</span>لا توجد بيانات</div>';return}c.innerHTML='';f.forEach(a=>{const ri=accounts.indexOf(a),uv=getUSD(a).toFixed(2),isS=a.type==='سوداني',tc='t-'+a.type.replace(' ','-');const card=document.createElement('div');card.className='ac';if(editIndex===ri){card.innerHTML='<div style="display:flex;flex-direction:column;gap:10px"><div class="ach"><span class="aci">#'+(ri+1)+'</span></div><div class="fg"><label>البريد</label><input type="email" id="eec" value="'+esc(a.email)+'" dir="ltr" style="padding:10px;border-radius:8px;border:1px solid #38bdf8;background:var(--ib);color:var(--tx)"></div><div class="fg"><label>النوع</label><select id="etc" onchange="toggleEditCard('+ri+')" style="padding:10px;border-radius:8px;border:1px solid #38bdf8;background:var(--ib);color:var(--tx)">'+AC.map(x=>'<option value="'+x+'"'+(a.type===x?' selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="fg" id="epcg-'+ri+'"'+(isS?' style="display:none"':'')+'><label>السعر</label><input type="number" id="epc" value="'+a.price+'" min="0" step="0.01" style="padding:10px;border-radius:8px;border:1px solid #38bdf8;background:var(--ib);color:var(--tx)"></div><div class="aca"><button class="save" onclick="saveEditCard('+ri+')">💾</button><button class="cancel" onclick="cancelEdit()">❌</button></div></div>'}else{const pd=isS?'<div class="emc">—</div>':'<div class="pc">'+CS[a.currency]+parseFloat(a.price).toFixed(2)+'</div>';const ud=isS?'<div class="emc">—</div>':'<div class="uc">$'+uv+'</div>';const dateHtml=a.created_at?'<div style="text-align:center;color:var(--tx2);font-size:.7rem">📅 '+formatDate(a.created_at)+'</div>':'';const ptsHtml=(typeof getPoints==='function'&&getPoints(a)>0)?'<div class="points-badge" style="text-align:center;margin-top:8px;color:#2dd4bf;font-size:.85rem;font-weight:700">⭐ '+getPoints(a)+' نقاط</div>':'';card.innerHTML='<div class="ach"><span class="aci">#'+(ri+1)+'</span><span class="typ '+tc+'">'+a.type+'</span></div><div class="ace"><span class="acet">'+esc(a.email)+'</span><button class="accp" onclick="copyEmail(\''+esc(a.email)+'\')">📋</button></div>'+ptsHtml+'<div class="acin"><div class="acii"><div class="acil">السعر</div>'+pd+'</div><div class="acii"><div class="acil">USD</div>'+ud+'</div></div>'+dateHtml+'<div class="aca"><button class="edit" onclick="startEdit('+ri+')">✏️</button><button class="del" onclick="deleteAccount('+ri+')">🗑️</button></div>'}c.appendChild(card)})}
function renderTable(f){const t2=document.getElementById('at');if(!t2)return;t2.innerHTML='';if(f.length===0){t2.innerHTML='<tr><td colspan="8" class="es"><span class="ic">📭</span>لا توجد بيانات</td></tr>';return}f.forEach(a=>{const ri=accounts.indexOf(a),uv=getUSD(a).toFixed(2),isS=a.type==='سوداني';const tr=document.createElement('tr');if(editIndex===ri){tr.innerHTML='<td>'+(ri+1)+'</td><td><input type="email" id="eet" value="'+esc(a.email)+'" dir="ltr" style="padding:6px 9px;border-radius:6px;border:1px solid #38bdf8;background:var(--ib);color:var(--tx);font-size:.82rem;width:100%"></td><td><select id="ett" onchange="toggleEditTable('+ri+')" style="padding:6px 9px;border-radius:6px;border:1px solid #38bdf8;background:var(--ib);color:var(--tx);font-size:.82rem;width:100%">'+AC.map(x=>'<option value="'+x+'"'+(a.type===x?' selected':'')+'>'+x+'</option>').join('')+'</select></td><td id="ept-'+ri+'">'+(isS?'<span class="emc">—</span>':'<input type="number" id="ept" value="'+a.price+'" min="0" step="0.01" style="padding:6px 9px;border-radius:6px;border:1px solid #38bdf8;background:var(--ib);color:var(--tx);font-size:.82rem;width:100%">')+'</td><td><span class="uc">—</span></td><td>—</td><td class="date-cell">'+formatDate(a.created_at)+'</td><td><div class="acs"><button class="save" onclick="saveEditTable('+ri+')">💾</button><button class="cancel" onclick="cancelEdit()">❌</button></div></td>'}else{const tc='t-'+a.type.replace(' ','-');const pd=isS?'<span class="emc">—</span>':'<span class="pc">'+CS[a.currency]+parseFloat(a.price).toFixed(2)+'</span>';const ud=isS?'<span class="emc">—</span>':'<span class="uc">$'+uv+'</span>';const pts=(typeof getPoints==='function')?getPoints(a):0;const ptsCell=pts>0?'⭐ '+pts:'—';tr.innerHTML='<td>'+(ri+1)+'</td><td class="ec"><div class="ecn"><span class="et">'+esc(a.email)+'</span><button class="cpb" onclick="copyEmail(\''+esc(a.email)+'\')">📋</button></div></td><td><span class="typ '+tc+'">'+a.type+'</span></td><td>'+pd+'</td><td>'+ud+'</td><td style="color:#2dd4bf;font-weight:700;text-align:center">'+ptsCell+'</td><td class="date-cell">'+formatDate(a.created_at)+'</td><td><div class="acs"><button class="edit" onclick="startEdit('+ri+')">✏️</button><button class="del" onclick="deleteAccount('+ri+')">🗑️</button></div></td>'}t2.appendChild(tr)})}
function renderCharts(){const c={أمريكي:0,'هونغ كونغ':0,ياباني:0,سوداني:0};accounts.forEach(a=>{if(c[a.type]!==undefined)c[a.type]++});const total=accounts.length;const pie=document.getElementById('pieChart');if(pie){if(total===0){pie.innerHTML='<text x="100" y="100" text-anchor="middle" fill="#94a3b8" font-size="14">لا توجد بيانات</text>'}else{const colors={'أمريكي':'#3b82f6','هونغ كونغ':'#ef4444','ياباني':'#f472b6','سوداني':'#22c55e'};let startAngle=-90,cx=100,cy=100,r=70,html='';Object.entries(c).forEach(([k,v])=>{if(v===0)return;const angle=(v/total)*360;const endAngle=startAngle+angle;const x1=cx+r*Math.cos(startAngle*Math.PI/180);const y1=cy+r*Math.sin(startAngle*Math.PI/180);const x2=cx+r*Math.cos(endAngle*Math.PI/180);const y2=cy+r*Math.sin(endAngle*Math.PI/180);const largeArc=angle>180?1:0;html+='<path d="M '+cx+' '+cy+' L '+x1+' '+y1+' A '+r+' '+r+' 0 '+largeArc+' 1 '+x2+' '+y2+' Z" fill="'+colors[k]+'" stroke="#0f172a" stroke-width="2"/>';const midAngle=(startAngle+endAngle)/2;const lx=cx+(r*0.65)*Math.cos(midAngle*Math.PI/180);const ly=cy+(r*0.65)*Math.sin(midAngle*Math.PI/180);html+='<text x="'+lx+'" y="'+ly+'" text-anchor="middle" fill="#fff" font-size="11" font-weight="bold">'+v+'</text>';startAngle=endAngle});pie.innerHTML=html}}
const bar=document.getElementById('barChart');if(bar){if(total===0){bar.innerHTML='<text x="200" y="100" text-anchor="middle" fill="#94a3b8" font-size="14">لا توجد بيانات</text>'}else{const colors={'أمريكي':'#3b82f6','هونغ كونغ':'#ef4444','ياباني':'#f472b6','سوداني':'#22c55e'};const maxV=Math.max(...Object.values(c),1);let bhtml='';let idx=0;Object.entries(c).forEach(([k,v])=>{const x=30+idx*90;const h=(v/maxV)*120;const y=160-h;bhtml+='<rect x="'+x+'" y="'+y+'" width="60" height="'+h+'" fill="'+colors[k]+'" rx="5"/>';bhtml+='<text x="'+(x+30)+'" y="'+(y-5)+'" text-anchor="middle" fill="#e2e8f0" font-size="12" font-weight="bold">'+v+'</text>';bhtml+='<text x="'+(x+30)+'" y="180" text-anchor="middle" fill="#94a3b8" font-size="10">'+k+'</text>';idx++});bar.innerHTML=bhtml}}}
function updateStats(){const tc=accounts.length,tu=accounts.reduce((s,a)=>s+getUSD(a),0),c={أمريكي:0,'هونغ كونغ':0,ياباني:0,سوداني:0};accounts.forEach(a=>{if(c[a.type]!==undefined)c[a.type]++});const e=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};e('tc',tc);e('tu','$'+tu.toFixed(2));e('ta',c['أمريكي']);e('th',c['هونغ كونغ']);e('tj',c['ياباني']);e('tsd',c['سوداني']);if(typeof getTotalPoints==='function')e('tp',getTotalPoints())}
function copyEmail(e){navigator.clipboard.writeText(e).then(()=>showToast('📋 تم النسخ')).catch(()=>{const tx=document.createElement('textarea');tx.value=e;document.body.appendChild(tx);tx.select();document.execCommand('copy');document.body.removeChild(tx);showToast('📋 تم النسخ')})}
async function addAccount(){const e=document.getElementById('ei').value.trim();const t2=document.getElementById('ti').value;const c=T2C[t2];const isS=t2==='سوداني';if(!e){showToast('⚠️ أدخل البريد','error');return}if(!isValidEmail(e)){showToast('⚠️ بريد غير صالح','error');return}let p='0';if(!isS){p=document.getElementById('pi').value.trim();if(p===''||parseFloat(p)<0){showToast('⚠️ أدخل سعر صحيح','error');return}p=parseFloat(p).toFixed(2)}if(accounts.some(a=>a.email.toLowerCase()===e.toLowerCase())){showToast('⚠️ البريد موجود','warning');return}const now=new Date().toISOString();accounts.push({email:e,type:t2,price:p,currency:isS?'FREE':c,tag:'',created_at:now});await saveData();renderAccounts();showToast(isS?'✅ تم إضافة سوداني':'✅ تم الإضافة');document.getElementById('ei').value='';document.getElementById('pi').value='';document.getElementById('ei').focus()}
async function bulkAdd(){const r=document.getElementById('bi').value.trim();const d=document.getElementById('bdt').value;const dup=document.getElementById('bda').value;if(!r){showToast('⚠️ الصق البيانات','error');return}const lines=r.split('\n').map(l=>l.trim()).filter(l=>l.length>0);let add=0,sk=0,up=0,inv=0;lines.forEach(l=>{const e=extractEmail(l);if(!e){inv++;return}const t2=extractType(l)||d;const c=extractCurrency(l)||T2C[t2]||'USD';const isS=t2==='سوداني';let p='0';if(!isS){const pp=extractPrice(l,e);if(pp===null){inv++;return}p=pp.toFixed(2)}const now=new Date().toISOString();const idx=accounts.findIndex(a=>a.email.toLowerCase()===e.toLowerCase());if(idx!==-1){if(dup==='skip')sk++;else{accounts[idx]={email:e,type:t2,price:p,currency:isS?'FREE':c,tag:accounts[idx].tag||'',created_at:accounts[idx].created_at||now};up++}}else{accounts.push({email:e,type:t2,price:p,currency:isS?'FREE':c,tag:'',created_at:now});add++}});await saveData();renderAccounts();let m='✅ '+add;if(up)m+=' | 🔄 '+up;if(sk)m+=' | ⏭️ '+sk;if(inv)m+=' | ❌ '+inv;showToast(m,(add||up)?'success':'warning');if(add||up)document.getElementById('bi').value=''}
function loadExample(){document.getElementById('bi').value='user99@hotmail.com 50 أمريكي\nkhaled_a@gmail.com 500 هونغ كونغ\nmohammed_99@outlook.com 3000 ياباني\nahmed@gmail.com سوداني\namjad1@gmail.com 200 أمريكي';showToast('📋 تم التحميل')}
function clearBulkInput(){document.getElementById('bi').value='';showToast('🧹 تم التفريغ')}
function startEdit(i){editIndex=i;renderAccounts()}
async function saveEditCard(i){const e=document.getElementById('eec').value.trim();const t2=document.getElementById('etc').value;const c=T2C[t2];const isS=t2==='سوداني';let p='0';if(!isS){const pi=document.getElementById('epc');if(!pi){showToast('⚠️','error');return}p=pi.value.trim();if(p===''||parseFloat(p)<0){showToast('⚠️ سعر غير صالح','error');return}p=parseFloat(p).toFixed(2)}if(!isValidEmail(e)){showToast('⚠️ بريد غير صالح','error');return}if(accounts.some((a,x)=>x!==i&&a.email.toLowerCase()===e.toLowerCase())){showToast('⚠️ البريد موجود','warning');return}accounts[i]={...accounts[i],email:e,type:t2,price:p,currency:isS?'FREE':c,tag:accounts[i].tag||''};editIndex=-1;await saveData();renderAccounts();showToast('✅ تم الحفظ')}
async function saveEditTable(i){const e=document.getElementById('eet').value.trim();const t2=document.getElementById('ett').value;const c=T2C[t2];const isS=t2==='سوداني';let p='0';if(!isS){const pi=document.getElementById('ept');if(!pi){showToast('⚠️','error');return}p=pi.value.trim();if(p===''||parseFloat(p)<0){showToast('⚠️ سعر غير صالح','error');return}p=parseFloat(p).toFixed(2)}if(!isValidEmail(e)){showToast('⚠️ بريد غير صالح','error');return}if(accounts.some((a,x)=>x!==i&&a.email.toLowerCase()===e.toLowerCase())){showToast('⚠️ البريد موجود','warning');return}accounts[i]={...accounts[i],email:e,type:t2,price:p,currency:isS?'FREE':c,tag:accounts[i].tag||''};editIndex=-1;await saveData();renderAccounts();showToast('✅ تم الحفظ')}
function cancelEdit(){editIndex=-1;renderAccounts()}
async function deleteAccount(i){if(confirm('حذف: '+accounts[i].email+'؟')){accounts.splice(i,1);await saveData();renderAccounts();showToast('🗑️ تم الحذف')}}
function openClearModal(){if(accounts.length===0){showToast('لا توجد بيانات','warning');return}document.getElementById('cm').classList.add('show')}
function closeClearModal(){document.getElementById('cm').classList.remove('show')}
async function confirmClearAll(){accounts=[];await saveData();renderAccounts();closeClearModal();showToast('🗑️ تم المسح')}
function toggleEditCard(i){const t2=document.getElementById('etc').value,isS=t2==='سوداني',g=document.getElementById('epcg-'+i);if(g){if(isS)g.style.display='none';else g.style.display='flex'}}
function toggleEditTable(i){const t2=document.getElementById('ett').value,isS=t2==='سوداني',c=document.getElementById('ept-'+i);if(!c)return;if(isS)c.innerHTML='<span class="emc">—</span>';else{const a=accounts[i];c.innerHTML='<input type="number" id="ept" value="'+a.price+'" min="0" step="0.01" style="padding:6px 9px;border-radius:6px;border:1px solid #38bdf8;background:var(--ib);color:var(--tx);font-size:.82rem;width:100%">'}}
function exportBackup(){if(accounts.length===0){showToast('لا توجد بيانات','error');return}const b={version:'v2',exportDate:new Date().toISOString(),accountsCount:accounts.length,accounts:accounts};const blob=new Blob([JSON.stringify(b,null,2)],{type:'application/json;charset=utf-8'});const link=document.createElement('a');const d=new Date().toISOString().slice(0,19).replace(/[:T]/g,'-');link.href=URL.createObjectURL(blob);link.download='نسخة_احتياطية_'+d+'.json';link.click();showToast('💾 تم التحميل')}
function triggerImport(){document.getElementById('if').click()}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async(ev)=>{try{const b=JSON.parse(ev.target.result);if(!b.accounts||!Array.isArray(b.accounts))throw new Error('bad');const merge=confirm('الملف فيه '+b.accounts.length+' حساب.\n\nOK = دمج\nCancel = استبدال');if(!merge){if(!confirm('استبدال كل البيانات؟'))return;accounts=b.accounts.map(a=>({...a,tag:a.tag||'',created_at:a.created_at||new Date().toISOString()}))}else{b.accounts.forEach(n=>{if(!accounts.some(a=>a.email.toLowerCase()===n.email.toLowerCase()))accounts.push({...n,tag:n.tag||'',created_at:n.created_at||new Date().toISOString()})})}await saveData();renderAccounts();showToast('✅ تم الاستيراد')}catch(err){showToast('❌ ملف غير صالح','error')}};r.readAsText(f);e.target.value=''}
function applyAdvancedFilter(){const pf=document.getElementById('pFrom').value;const pt=document.getElementById('pTo').value;const df=document.getElementById('dFrom').value;const dt=document.getElementById('dTo').value;advancedFilter={active:true,priceFrom:pf?parseFloat(pf):null,priceTo:pt?parseFloat(pt):null,dateFrom:df||null,dateTo:dt||null};renderAccounts();showToast('🔍 تم التطبيق','info')}
function clearAdvancedFilter(){advancedFilter={active:false,priceFrom:null,priceTo:null,dateFrom:null,dateTo:null};['pFrom','pTo','dFrom','dTo'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});renderAccounts();showToast('🧹 تم المسح','info')}
function exportToHTML(){if(accounts.length===0){showToast('لا توجد بيانات','error');return}const tu=accounts.reduce((s,a)=>s+getUSD(a),0);const c={أمريكي:0,'هونغ كونغ':0,ياباني:0,سوداني:0};accounts.forEach(a=>{if(c[a.type]!==undefined)c[a.type]++});const now=new Date().toLocaleString('ar-EG');let h='<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><title>تقرير</title><style>body{font-family:sans-serif;background:#f0f4f8;padding:25px;color:#1e293b}table{width:100%;border-collapse:collapse;background:#fff;border-radius:10px;overflow:hidden}thead{background:#1e293b;color:#fff}th,td{padding:10px;text-align:right}td{border-bottom:1px solid #e2e8f0}</style></head><body><h1>📊 تقرير الحسابات</h1><p>'+now+'</p><p>الإجمالي: '+accounts.length+' حساب | $'+tu.toFixed(2)+'</p><table><thead><tr><th>#</th><th>البريد</th><th>النوع</th><th>السعر</th><th>بالدولار</th><th>⭐ نقاط</th><th>تاريخ</th></tr></thead><tbody>';accounts.forEach((a,i)=>{const isS=a.type==='سوداني',usd=getUSD(a).toFixed(2),pd=isS?'—':CS[a.currency]+parseFloat(a.price).toFixed(2),ud=isS?'—':'$'+usd,pts=(typeof getPoints==='function')?getPoints(a):0;h+='<tr><td>'+(i+1)+'</td><td>'+esc(a.email)+'</td><td>'+a.type+'</td><td>'+pd+'</td><td>'+ud+'</td><td>⭐ '+pts+'</td><td>'+formatDate(a.created_at)+'</td></tr>'});h+='</tbody></table></body></html>';const b=new Blob([h],{type:'text/html;charset=utf-8'}),l=document.createElement('a');l.href=URL.createObjectURL(b);l.download='تقرير_'+new Date().toISOString().slice(0,10)+'.html';l.click();showToast('🌐 HTML')}
function exportToPDF(){if(accounts.length===0){showToast('لا توجد بيانات','error');return}showToast('📄 جاري التجهيز','info');setTimeout(()=>window.print(),400)}
function exportToCSV(){if(accounts.length===0){showToast('لا توجد بيانات','error');return}let csv='\uFEFF'+'م,البريد,النوع,السعر,العملة,بالدولار,نقاط,تاريخ\n';accounts.forEach((a,i)=>{const pts=(typeof getPoints==='function')?getPoints(a):0;csv+=(i+1)+',"'+a.email+'","'+a.type+'","'+a.price+'","'+(a.currency||'FREE')+'","'+getUSD(a).toFixed(2)+'","'+pts+'","'+formatDate(a.created_at)+'"\n'});const t2=accounts.reduce((s,a)=>s+getUSD(a),0);csv+='\n"","الإجمالي","","","","'+t2.toFixed(2)+'"\n';const b=new Blob([csv],{type:'text/csv;charset=utf-8'}),l=document.createElement('a');l.href=URL.createObjectURL(b);l.download='حسابات_'+new Date().toISOString().slice(0,10)+'.csv';l.click();showToast('📥 CSV')}
(async()=>{try{await openIDB()}catch(e){console.error(e)}await loadData();if(typeof applyLang==='function')applyLang();if(typeof addAuthButton==='function')addAuthButton();updateFF();renderAccounts();if(navigator.onLine)setSS('offline');window.addEventListener('online',()=>setSS('syncing'));window.addEventListener('offline',()=>setSS('offline'))})();
