const AUTH_KEY='amjad_auth_password',AUTH_SESSION='amjad_auth_session',SESSION_TIMEOUT=864e5;
function isAuthEnabled(){return!!localStorage.getItem(AUTH_KEY)}
function isLoggedIn(){const s=localStorage.getItem(AUTH_SESSION);if(!s)return!1;try{const d=JSON.parse(s);if(Date.now()-d.time>SESSION_TIMEOUT){localStorage.removeItem(AUTH_SESSION);return!1}return!0}catch(e){return!1}}
function setPassword(p){localStorage.setItem(AUTH_KEY,btoa(p))}
function checkPassword(p){const s=localStorage.getItem(AUTH_KEY);if(!s)return!1;return s===btoa(p)}
function login(){localStorage.setItem(AUTH_SESSION,JSON.stringify({time:Date.now()}))}
function logout(){localStorage.removeItem(AUTH_SESSION);location.reload()}
function showLoginScreen(){if(isLoggedIn())return;document.body.innerHTML='<div style="min-height:100vh;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#0f172a,#1e1b4b);padding:20px"><div style="background:rgba(30,41,59,.95);padding:35px;border-radius:20px;max-width:400px;width:100%;border:1px solid rgba(51,65,85,.6);box-shadow:0 25px 50px rgba(0,0,0,.5);text-align:center"><div style="font-size:3rem;margin-bottom:15px">🔐</div><h1 style="color:#e2e8f0;font-size:1.4rem;margin-bottom:8px">إدارة الحسابات</h1><p style="color:#94a3b8;font-size:.85rem;margin-bottom:25px">أدخل كلمة السر للدخول</p><input type="password" id="pwInput" placeholder="كلمة السر" style="width:100%;padding:14px;border-radius:12px;border:1px solid #475569;background:#1e293b;color:#e2e8f0;font-size:1rem;outline:none;text-align:center;margin-bottom:15px" autofocus><button onclick="tryLogin()" style="width:100%;padding:14px;border:none;border-radius:12px;background:linear-gradient(135deg,#38bdf8,#2563eb);color:#fff;font-weight:700;font-size:1rem;cursor:pointer">دخول</button><p id="errMsg" style="color:#ef4444;font-size:.85rem;margin-top:12px;min-height:20px"></p></div></div>';document.getElementById('pwInput').addEventListener('keypress',e=>{if(e.key==='Enter')tryLogin()});document.getElementById('pwInput').focus()}
function tryLogin(){const p=document.getElementById('pwInput').value;if(checkPassword(p)){login();location.reload()}else{document.getElementById('errMsg').textContent='❌ كلمة السر غلط!';document.getElementById('pwInput').value='';document.getElementById('pwInput').focus()}}
function enablePassword(){const p=prompt('أدخل كلمة السر الجديدة:');if(!p||p.length<4){alert('كلمة السر قصيرة!');return}const c=prompt('أعد كتابة كلمة السر:');if(p!==c){alert('غير متطابقتين!');return}setPassword(p);login();alert('✅ تم تفعيل كلمة السر!');location.reload()}
function disablePassword(){const p=prompt('أدخل كلمة السر الحالية:');if(!checkPassword(p)){alert('❌ غلط!');return}localStorage.removeItem(AUTH_KEY);localStorage.removeItem(AUTH_SESSION);alert('✅ تم إلغاء كلمة السر!');location.reload()}
function addAuthButton(){const ha=document.querySelector('.hd-actions');if(!ha)return;const b=document.createElement('button');b.className='ib';if(isAuthEnabled()){b.title='خروج';b.innerHTML='🚪';b.onclick=logout}else{b.title='تفعيل كلمة السر';b.innerHTML='🔓';b.onclick=enablePassword}ha.insertBefore(b,ha.firstChild)}